### ISSUE TITLE
So what is the better Vue, React or Angular? :)

### ISSUE THREAD

**Issue by BotanMan** [temirka13/Movie-loader#1]
Привет
Мы, тут немного расширяемся, ищем энергичных и желающих развиваться Jun-Middlов :)

Интересно?

Devhouse, г.Ставрополь
ул. Маршала Жукова 22.

**Comment by temirka13** [comment]
@BotanMan Привет! Интересно, можем созвониться и обсудить) (мой номер - 89286318255)

**Comment by temirka13** [comment]
For me:
1) Vue - because it is simple, understandable and convenient, you don’t have to worry much about optimization, but unfortunately it doesn’t have such a large community like React.
2) React - a lot of cool plugins, support from a large company, big community, but unfortunately the entry threshold is more than Vue.js
3) Angular - very little use it, so there is not much to say.
